title: "Ministry of Justice Security Guidance"
show_govuk_logo: true

plugins:
  - jekyll-redirect-from

permalink: pretty

defaults:
  -
    scope:
      path: "standards"
    values:
      standard: true
  -
    scope:
      path: "guides"
    values:
      guide: true
  -
    scope:
      path: "principles"
    values:
      principle: true
  -
    scope:
      path: "suppliers"
    values:
      supplier: true
  -
    scope:
      path: "mythbusting"
    values:
      mythbusting: true
  -
    scope:
      path: "contact"
    values:
      contact: true
  -
    scope:
      path: "policies"
    values:
      policy: true
